# -*- coding: utf-8 -*-
"""NLP_6B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yM9F1Dg5eWUWvjp5HWKpPCFLHPQIPVXm
"""

from IPython.display import HTML, display
def set_css():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', set_css)

"""# 6. Illustrate part of speech tagging.

## b) Named Entity recognition using user defined text.
"""

# Install and download spaCy model
# !pip install -U spacy
# !python -m spacy download en_core_web_sm

import spacy

# Load English tokenizer, tagger, parser, and NER
nlp = spacy.load("en_core_web_sm")

# Process whole documents
text = (
    "When Sebastian Thrun started working on self-driving cars at "
    "Google in 2007, few people outside of the company took him "
    "seriously. “I can tell you very senior CEOs of major American "
    "car companies would shake my hand and turn away because I wasn’t "
    "worth talking to,” said Thrun, in an interview with Recode earlier "
    "this week."
)
doc = nlp(text)

# Analyse syntax
print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])
print("Verbs:", [token.lemma_ for token in doc if token.pos_ == "VERB"])